export const vendors = [
    {
    ID: 1,
    TypeOfMeeting: 'DRM',
    // TotalTimeSpentInAnchoredMeetings: '0',
    DocumentUploaded: '3',
    MeetingTitle: 'DRM1',
    InvitedNoOfMeetings: '0',
    AttendedtedNoOfMeetings: '1',
    ScheduleNoOfMeetings: '1',
    ConductedNoOfMeetings: '1',
    TotalTimeSpent: '1 Hr',
  }, {
    ID: 2,
    TypeOfMeeting: 'IRM',
    // TotalTimeSpentInAnchoredMeetings: '2',
    DocumentUploaded: '0',
    MeetingTitle: 'IRM1',
    InvitedNoOfMeetings: '0',
    AttendedtedNoOfMeetings: '0',
    ScheduleNoOfMeetings: '1',
    ConductedNoOfMeetings: '1',
    TotalTimeSpent: '1 Hr',
  }, {
    ID: 3,
    TypeOfMeeting: 'DRM',
    // TotalTimeSpentInAnchoredMeetings: '0',
    DocumentUploaded: '0',
    MeetingTitle: 'DRM2',
    InvitedNoOfMeetings: '0',
    AttendedtedNoOfMeetings: '2',
    ScheduleNoOfMeetings: '1',
    ConductedNoOfMeetings: '1',
    TotalTimeSpent: '1 Hr',
  }, {
    ID: 4,
    TypeOfMeeting: 'IRM',
    // TotalTimeSpentInAnchoredMeetings: '0',
    DocumentUploaded: '0',
    MeetingTitle: 'IRM2',
    InvitedNoOfMeetings: '3',
    AttendedtedNoOfMeetings: '0',
    ScheduleNoOfMeetings: '1',
    ConductedNoOfMeetings: '1',
    TotalTimeSpent: '3 Hr',
  }, {
    ID: 5,
    TypeOfMeeting: 'DRM',
    // TotalTimeSpentInAnchoredMeetings: '0',
    DocumentUploaded: '0',
    MeetingTitle: 'DRM3',
    InvitedNoOfMeetings: '0',
    AttendedtedNoOfMeetings: '0',
    ScheduleNoOfMeetings: '1',
    ConductedNoOfMeetings: '1',
    TotalTimeSpent: '1 Hr',
  }
];