CREATE TYPE [dbo].[UDT_TaskFileUpload] AS TABLE
(
	MeetingId BIGINT NOT NULL DEFAULT 0,
	TaskId BIGINT NOT NULL DEFAULT 0,
	[FileName] NVARCHAR(200) NULL,
	FileUrl NVARCHAR(500) NULL,
	ContentType NVARCHAR(200) NULL
)