export const customers = [
    {
    ID: 1,
    TypeOfMeeting: 'DRM',
    Closed: '0',
    OpenAndInprogress: '3',
    MeetingTitle: 'DRM1',
    BehindSchedule: '0',
    Closed: '1',
    TotalTask: '1',
    OpenAndBehindSchedule: '1',
    Inprogress: '1 Hr',
  }, {
    ID: 2,
    TypeOfMeeting: 'IRM',
    Closed: '2',
    OpenAndInprogress: '0',
    MeetingTitle: 'IRM1',
    BehindSchedule: '0',
    Closed: '0',
    TotalTask: '1',
    OpenAndBehindSchedule: '1',
    Inprogress: '1 Hr',
  }, {
    ID: 3,
    TypeOfMeeting: 'DRM',
    Closed: '0',
    OpenAndInprogress: '0',
    MeetingTitle: 'DRM2',
    BehindSchedule: '0',
    Closed: '2',
    TotalTask: '1',
    OpenAndBehindSchedule: '1',
    Inprogress: '1 Hr',
  }, {
    ID: 4,
    TypeOfMeeting: 'IRM',
    Closed: '0',
    OpenAndInprogress: '0',
    MeetingTitle: 'IRM2',
    BehindSchedule: '3',
    Closed: '0',
    TotalTask: '1',
    OpenAndBehindSchedule: '1',
    Inprogress: '3 Hr',
  }, {
    ID: 5,
    TypeOfMeeting: 'DRM',
    Closed: '0',
    OpenAndInprogress: '0',
    MeetingTitle: 'DRM3',
    BehindSchedule: '0',
    Closed: '0',
    TotalTask: '1',
    OpenAndBehindSchedule: '1',
    Inprogress: '1 Hr',
  }
];