CREATE TABLE [dbo].[Trn_TaskHistoryDetails]
(
	[HistoryId] INT NOT NULL PRIMARY KEY IDENTITY,
	[TaskId] BIGINT NULL,
	[ProgressId] BIGINT NULL,
	[StatusId] INT NULL, 
    [PriorityId] INT NULL, 
    [RoleId] INT NULL,
    [TaskRefNo] VARCHAR(50) NULL,
    [TaskUnqId] UNIQUEIDENTIFIER NULL,
    [ParentTaskId] BIGINT NULL,
	[TaskSubject] NVARCHAR(200) NULL,
    [TaskDesc] NVARCHAR(500) NULL,
    [InitialTargetDate] DATETIME NULL,
    [CurrentTargetDate] DATETIME NULL,
    [AssignerName] NVARCHAR(100) NULL,
    [AssignerEmail] NVARCHAR(100) NULL,
    [AssignerUPN] NVARCHAR(50) NULL,
    [AssignerADID] NVARCHAR(50) NULL,
    [AssigneeName] NVARCHAR(100) NULL,
    [AssigneeEmail] NVARCHAR(100) NULL,
    [AssigneeUPN] NVARCHAR(50) NULL,
    [AssigneeADID] NVARCHAR(50) NULL,
    [CoordinatorName] NVARCHAR(100) NULL,
    [CoordinatorEmail] NVARCHAR(100) NULL,
    [CoordinatorUPN] NVARCHAR(50) NULL,
    [CoordinatorADID] NVARCHAR(50) NULL,
    [CollaboratorName] NVARCHAR(100) NULL,
    [CollaboratorEmail] NVARCHAR(100) NULL,
    [CollaboratorUPN] NVARCHAR(50) NULL,
    [CollaboratorADID] NVARCHAR(50) NULL,
    [TransactionId] UNIQUEIDENTIFIER NULL
)
