CREATE TABLE [dbo].[Trn_TaskDetails]
(
	[TaskId] BIGINT NOT NULL PRIMARY KEY IDENTITY,
    [TaskRefNo] VARCHAR(50) NULL,
    [TaskUnqId] UNIQUEIDENTIFIER NULL,
    [StatusId] INT NULL, 
    [PriorityId] INT NULL, 
    [RoleId] INT NULL, 
    [ParentTaskId] BIGINT NULL, 
    [IsActive] BIT NULL, 
    [CreatedOnIST] DATETIME NULL, 
    [CreatedOnUTC] DATETIME NULL, 
    [CreatedByName] NVARCHAR(100) NULL,
    [CreatedByEmail] NVARCHAR(100) NULL,
    [CreatedByUPN] NVARCHAR(100) NULL,
    [CreatedByADID] NVARCHAR(50) NULL,
    [TaskSubject] NVARCHAR(200) NULL,
    [TaskDesc] NVARCHAR(500) NULL,
    [InitialTargetDate] DATETIME NULL,
    [CurrentTargetDate] DATETIME NULL,
    [AssignerName] NVARCHAR(100) NULL,
    [AssignerEmail] NVARCHAR(100) NULL,
    [AssignerUPN] NVARCHAR(100) NULL,
    [AssignerADID] NVARCHAR(50) NULL,
    [AssigneeName] NVARCHAR(100) NULL,
    [AssigneeEmail] NVARCHAR(100) NULL,
    [AssigneeUPN] NVARCHAR(100) NULL,
    [AssigneeADID] NVARCHAR(50) NULL,
    [CoordinatorName] NVARCHAR(100) NULL,
    [CoordinatorEmail] NVARCHAR(100) NULL,
    [CoordinatorUPN] NVARCHAR(100) NULL,
    [CoordinatorADID] NVARCHAR(50) NULL,
    [CollaboratorName] NVARCHAR(100) NULL,
    [CollaboratorEmail] NVARCHAR(100) NULL,
    [CollaboratorUPN] NVARCHAR(50) NULL,
    [CollaboratorADID] NVARCHAR(100) NULL,
    [TransactionId] UNIQUEIDENTIFIER NULL
)
